NAME = "001_create_books"


def up(connection):
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS books(
            book_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            isbn VARCHAR(255) NOT NULL UNIQUE
                CHECK (length(trim(isbn)) > 0),
            title VARCHAR(255) NOT NULL
                CHECK (length(trim(title)) > 0),
            author VARCHAR(255) NOT NULL
                CHECK (length(trim(author)) > 0)
        )
        """)
