NAME = "002_create_copies"


def up(connection):
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS copies(
            copy_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id INTEGER NOT NULL,
            available BOOLEAN NOT NULL DEFAULT TRUE,
            FOREIGN KEY (book_id)
                REFERENCES books(book_id)
        )
        """)
