NAME = "003_create_users"


def up(connection):
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users(
            user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL
                CHECK (length(trim(name)) > 0),
            role VARCHAR(20) NOT NULL
                CHECK (role IN ('student', 'professor'))
        )
        """)
